### ISSUE TITLE
Some questions about data processing.

### ISSUE THREAD

**Issue by fxqzb** [yunhe20/D-PCC#1]
Dear Yun He,

Hello! Thanks for your good job!

I have some questions about the data processing step.

In _prepare_semantickitti.py__, the points are normalized and multiplied by map_size:

`xyzs, meta_data = normalize_pcd(xyzs)`
`map_xyzs = xyzs * (map_size)`
`xyzs = np.floor(map_xyzs).astype('float32')`

After this step, I find that the points in a point cloud may miss a lot, from 120,000 points to 2,000 points. I think this processing process will influence the training performance. Do I understand correctly?

Besides, could you mind uploading the processed datasets and the best checkpoints? It will be helpful for me.

Thank you!
Xiaoqing

**Comment by skyqwe123** [comment]
@yunhe20 Thanks for your good job!  I looked at the way you handled the data and I was wondering why you did it, any enlightening experiences to share?
