### ISSUE TITLE
The code about qualitative results

### ISSUE THREAD

**Issue by yangpanquan** [yunhe20/D-PCC#6]
Hi, It's a great a job.And I am interested in your work.Your qualitative result is so good. So,can you upload your visualization code about qualitative result?

**Comment by yunhe20** [comment]
Thanks for your attention. If you refer to the Figure 6, we first calculate the distances from the decompressed points to the nearest groundtruth points. And then map the distances to the color space. To generate the colormap, we use the vedo library. Please refer to the [cmap function](https://vedo.embl.es/autodocs/content/vedo/pointcloud.html#vedo.pointcloud.Points.cmap) for more details.

**Comment by yangpanquan** [comment]
Thank you for your reply.But I still don't know how to reproduce your visualization code.I'm a freshman.If it's possible, can you upload your code about this?

**Comment by yangpanquan** [comment]
Besides, how do you get the picture of each stage of encoder or decoder(i.e. stage0,stage1,stage2 in figure2) ?
Can you also provide the code about this part?
