### ISSUE TITLE
Excluded scans  when K > 50000

### ISSUE THREAD

**Issue by miryalkarakshay** [yunhe20/D-PCC#9]
Hello,

Thank you for the amazing work. I was going through your prepare_semantickitti code and have a doubt about why you excluded certain scans if K>50000. 

Line: https://github.com/yunhe20/D-PCC/blob/23f0b85cfbf827004872dd7195610f37f704ebc2/prepare_semantickitti.py#L159

From what I could understand from the code K tells you how many points have been assigned to each valid cube. Did you reject the scans where more than 50,000 points have been assigned to a cube because they were simply too dense?

Could you please tell us the reason for this choice?

Thanks!

**Comment by yunhe20** [comment]
Sorry for the late reply. There are some bugs in the previous data process files and I have updated them. Actually, we set a parameter "max_num" to control the maximum point number in each cube, and its default value is 500000. But if your GPU memory is relatively small (eg, < 30GB), you may encounter the OOM (out of memory) issue when compress dense point cloud cubes. Thus you can adjust the "max_num" parameter according to your device.

**Comment by miryalkarakshay** [comment]
Thank you for the clarification that helps! :)

**Comment by yimjae0** [comment]
Hello,

Are the results in the paper based on using all of the data? When I run your code, I get better performance than the results in the paper

Thanks!
